name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: www

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - name: Checkout Source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Show NodeJS & NPM versions
        run: node --version && npm --version

      - name: Install Dependencies
        run: npm ci

      - name: Run unit tests and generate coverage report
        run: npm run test:coverage

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
