name: Frontend Tests

on:
  pull_request:

jobs:
  frontend-tests:
    defaults:
      run:
        working-directory: www

    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup NodeJS 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Show NodeJS & NPM versions
        run: node --version && npm --version

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm ci

      - name: Run unit tests and generate coverage report
        run: npm run test:coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
